---
# File 2: cronjob.yaml (in your git repo under tracking-demo/)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: report-generator
  namespace: demo
  labels:
    app: report-generator
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: report-generator
    spec:
      template:
        metadata:
          labels:
            app: report-generator
        spec:
          serviceAccountName: report-generator
          containers:
          - name: generator
            image: bitnami/kubectl:latest
            command:
            - /bin/bash
            - -c
            - |
              # Get the CronJob UID for ownerReference
              CRONJOB_UID=$(kubectl get cronjob report-generator -n demo -o jsonpath='{.metadata.uid}')
              TIMESTAMP=$(date +%s)
              
              # Create a ConfigMap with proper tracking
              cat <<EOF | kubectl apply -f -
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: report-${TIMESTAMP}
                namespace: demo
                labels:
                  app: report-generator
                  generated-by: cronjob
                  argocd.argoproj.io/instance: tracking-demo
                annotations:
                  argocd.argoproj.io/tracking-id: "tracking-demo:v1/ConfigMap:demo/report-${TIMESTAMP}"
                ownerReferences:
                - apiVersion: batch/v1
                  kind: CronJob
                  name: report-generator
                  uid: ${CRONJOB_UID}
              data:
                timestamp: "${TIMESTAMP}"
                report: "Generated at ${TIMESTAMP}"
              EOF
          restartPolicy: OnFailure

---
# File 3: rbac.yaml (in your git repo)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: report-generator
  namespace: demo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: report-generator
  namespace: demo
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "list", "patch", "update"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: report-generator
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: report-generator
subjects:
- kind: ServiceAccount
  name: report-generator
  namespace: demo

